plugins {
    id "net.fabricmc.fabric-loom" version "${loom_version}"
    id "maven-publish"
}

base {
    archivesName = "seeu-extra-fabric"
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "seeu_extra" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

sourceSets.client.java.srcDir(project(":common").file("src/client/java"))
sourceSets.main.java.srcDir(project(":common").file("src/server/java"))

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(project.java_version as int)
    }

    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = project.java_version as int
}

tasks.named("jar") {
    from(project(":common").sourceSets.main.output)
}

tasks.named("sourcesJar") {
    from(project(":common").sourceSets.main.allSource)
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    clientImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    clientImplementation "net.fabricmc.fabric-api:fabric-rendering-v1:${project.fabric_rendering_api_version}"

    implementation project(":common")
    clientImplementation project(":common")
    compileOnly "dev.keryeshka.seeu:seeu-addon-api:${project.seeu_release_tag}@jar"
    clientCompileOnly "dev.keryeshka.seeu:seeu-addon-api:${project.seeu_release_tag}@jar"
}

processResources {
    def addonVersion = project.seeu_extra_version
    def minecraftVersion = project.minecraft_version
    def loaderVersion = project.loader_version
    inputs.property "version", addonVersion
    inputs.property "minecraft_version", minecraftVersion
    inputs.property "loader_version", loaderVersion

    filesMatching("fabric.mod.json") {
        expand(
                version: addonVersion,
                minecraft_version: minecraftVersion,
                loader_version: loaderVersion
        )
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = base.archivesName.get()
            from components.java
        }
    }
}
