allprojects {
    group = project.maven_group
    version = project.seeu_extra_version

    tasks.withType(Jar).configureEach {
        if (rootProject.file("LICENSE").exists()) {
            from(rootProject.file("LICENSE")) {
                into("META-INF")
            }
        }
    }

    repositories {
        exclusiveContent {
            forRepository {
                ivy {
                    name = "SeeUGitHubReleases"
                    url = uri("https://github.com/cat4blep/SeeU/releases/download")
                    patternLayout {
                        artifact("[revision]/[module]-[revision].[ext]")
                    }
                    metadataSources {
                        artifact()
                    }
                }
            }

            filter {
                includeModule("dev.keryeshka.seeu", "seeu-addon-api")
            }
        }

        mavenCentral()
        maven { url = "https://maven.neoforged.net/releases" }
        maven { url = "https://maven.fabricmc.net/" }
    }
}
